# Generated by Django 5.1.1 on 2025-12-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('dog_owners', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alojamiento', 'Alojamiento'), ('playa', 'Playa'), ('veterinaria', 'Veterinaria'), ('ruta', 'Ruta'), ('transporte', 'Transporte'), ('espacio-natural', 'Espacio Natural'), ('hosteleria', 'Hostelería'), ('tienda', 'Tienda'), ('servicio', 'Servicio'), ('comunidad', 'Comunidad')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('location', models.JSONField()),
                ('pet_rules', models.JSONField()),
                ('contact', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('season_access', models.BooleanField(blank=True, null=True)),
                ('ppp_allowed', models.BooleanField(blank=True, null=True)),
                ('special_regulations', models.JSONField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('water_access', models.BooleanField(blank=True, null=True)),
                ('suitable_for', models.JSONField(blank=True, null=True)),
                ('transport_policies', models.JSONField(blank=True, null=True)),
                ('regulations', models.JSONField(blank=True, null=True)),
                ('activities', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
    ]
